### ISSUE TITLE
Scaled up drawer.shape() has blurry edges

### ISSUE THREAD

**Issue by hamoid** [openrndr/openrndr#115]
Edges of scaled shapes can look blurry

Ideally drawing a circle via `drawer.circle()` and via `drawer.shape()` would look the same in **size** and **sharpness**.

### Test program

```
package simpleTests

import org.openrndr.application
import org.openrndr.draw.*
import org.openrndr.extensions.Screenshots
import org.openrndr.shape.Circle
import kotlin.math.sin

fun main() {
    application {
        program {
            val circle = Circle(0.0, 0.0, 10.0)

            extend(Screenshots())
            extend {
                drawer.stroke = null

                drawer.isolated {
                    translate(bounds.center - 100.0)
                    scale(11.0 + 10 * sin(seconds))
                    shape(circle.shape)
                }

                drawer.isolated {
                    translate(bounds.center + 100.0)
                    scale(11.0 + 10 * sin(seconds))
                    circle(circle)
                }
            }
        }
    }
}
```

### Current output

![simpleTests TestShapeScaling-2020-05-26-10 49 17](https://user-images.githubusercontent.com/108264/82881077-81f08100-9f3f-11ea-881d-3fbeb1f484c1.png)

**Comment by edwinRNDR** [comment]
@hamoid I have addressed scaling issues a couple of weeks ago. May need to verify if it works sufficiently well

**Comment by hamoid** [comment]
Hi! How does the program above look for you now? For me it's like this:
![apps simpleTests ShapeScaling-2020-08-17-16 56 10](https://user-images.githubusercontent.com/108264/90410399-99f12000-e0aa-11ea-949f-dd96ef02ada1.png)
It seems to be somewhat different, but the scaled shape is still not sharp-edged like the other one.

**Comment by hamoid** [comment]
I don't know if this should be affected or not, but leave it here just in case:
![apps2 ContourStrokeDifferences-2020-08-17-16 59 14](https://user-images.githubusercontent.com/108264/90410736-05d38880-e0ab-11ea-8d43-082895c6ed0d.png)

```kotlin
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.extensions.Screenshots
import org.openrndr.shape.Circle

/**
 * stroke color looks different on contours depending on presence of fill
 */

fun main() = application {
    program {
        val c = Circle(200.0, 200.0, 100.0).contour
        extend(Screenshots())
        extend {
            drawer.run {
                clear(ColorRGBa.WHITE)
                stroke = ColorRGBa.BLACK.opacify(0.5)
                fill = ColorRGBa.WHITE
                contour(c)
                translate(210.0, 0.0)
                fill = null
                contour(c)
            }
        }
    }
}
```

**Comment by edwinRNDR** [comment]
> Hi! How does the program above look for you now? For me it's like this:
> ![apps simpleTests ShapeScaling-2020-08-17-16 56 10](https://user-images.githubusercontent.com/108264/90410399-99f12000-e0aa-11ea-949f-dd96ef02ada1.png)
> It seems to be somewhat different, but the scaled shape is still not sharp-edged like the other one.

Looks like I only fixed it for `drawer.contour`. Will look into what's up

**Comment by edwinRNDR** [comment]
https://github.com/openrndr/openrndr/commit/3621e89ed3472211e31356be8dd4936fe06f0df3  should improve things

**Comment by hamoid** [comment]
Now the borders look sharp :)
![apps simpleTests ShapeScaling-2020-08-17-22 42 15](https://user-images.githubusercontent.com/108264/90442497-0d128a80-e0db-11ea-80df-d16622745cd5.png)

What about the size difference?

```
import org.openrndr.application
import org.openrndr.color.ColorRGBa
import org.openrndr.draw.*
import org.openrndr.extensions.Screenshots
import org.openrndr.shape.Circle
import org.openrndr.shape.Rectangle
import kotlin.math.sin

fun main() {
    application {
        program {
            val circle = Circle(0.0, 0.0, 10.0)

            extend(Screenshots())
            extend {
                drawer.stroke = null
                val k = 11.0 + 10 * sin(seconds)

                drawer.isolated {
                    translate(bounds.position(0.2, 0.5))
                    scale(k)
                    shape(circle.shape)
                }

                drawer.isolated {
                    translate(bounds.position(0.8, 0.5))
                    scale(k)
                    circle(circle)
                }

                drawer.isolated {
                    stroke = ColorRGBa.WHITE
                    fill = null
                    rectangle(Rectangle.fromCenter(bounds.center, 2000.0, 2 * 10.0 * k))
                }
            }
        }
    }
}
```

**Comment by hamoid** [comment]
I guess the last issue above with the size comes from https://github.com/openrndr/openrndr/issues/122 but amplified up to 21 times by the scaling.

**Comment by hamoid** [comment]
BTW. The new sharp circle above on the left: could it be more antialiased?

**Comment by hamoid** [comment]
Now the borders look sharp! Yay! :)
